---
schema_version: "1"
document_type: meta
project_id: 01KF9GDH0ZCA6HSJHEX7VWF3SN
path_hash: 7e3588ce5e77a23a
created_at: "2026-01-18T13:33:14-08:00"
tool_version: 0.1.0
languages:
    - name: Go
      indicators:
        - go.mod
        - go.sum
---
schema_version: "1"
timestamp: "2026-01-18T13:28:55-08:00"
commit_hash: 561b68fa2a274b19d322b217ca62285c2d1c8898
files_changed:
    - path: pkg/generators/css.go
      additions: 31
      deletions: 0
    - path: pkg/tokens/components.go
      additions: 2
      deletions: 2
changes:
    - summary: Add CSS generation for component-level states
      details: States like 'error', 'active', 'has-toggle' can now be defined in component token files and will generate corresponding CSS classes. Previously the 'states' field was reserved but not processed.
      change_type: feature
      scope: pkg/generators
    - summary: Change States field type to support CSS generation
      details: Changed States from map[string]any to map[string]VariantDef to enable proper parsing of $class and CSS properties, matching how variants and sizes work.
      change_type: feature
      scope: pkg/tokens
next_steps:
    - summary: Document states section in token format documentation
      details: Update TOKENS.md to show states alongside variants and sizes
      priority: med
      scope: docs
---
schema_version: "1"
timestamp: "2026-01-20T08:37:31-08:00"
commit_hash: 54b6e6fbf572e004e61fcdfb044e0c81aff2531b
changes:
    - summary: Add @keyframes support for CSS animations
      details: Parse 'keyframes' sections from token JSON files and generate CSS @keyframes blocks. Added KeyframeDefinition type with Name and Frames fields, ExtractKeyframes function to scan dictionaries, and GenerateKeyframesCSS to output formatted CSS. Frames are automatically sorted by percentage (from=0%, to=100%).
      change_type: feature
      scope: pkg/tokens
    - summary: Integrate keyframes into CSS and Tailwind generators
      details: Added Keyframes field to GenerationContext. Both CSSGenerator and TailwindGenerator now call tokens.GenerateKeyframesCSS after @property declarations. Keyframes are output before @layer reset as global definitions.
      change_type: feature
      scope: pkg/generators
    - summary: Extract and pass keyframes in build command
      details: Call tokens.ExtractKeyframes(baseDict) in build.go and include in GenerationContext for CSS/Tailwind generation.
      change_type: feature
      scope: cmd/tokenctl
    - summary: Add keyframes unit tests
      details: Added TestExtractKeyframes_Basic, TestExtractKeyframes_Multiple, TestExtractKeyframes_Empty, TestGenerateKeyframesCSS, TestGenerateKeyframesCSS_FrameOrder, TestGenerateKeyframesCSS_FromTo in keyframes_test.go. Added TestCSSGenerator_Generate_WithKeyframes in css_test.go.
      change_type: feature
      scope: pkg/tokens,pkg/generators
    - summary: Document @keyframes in README and TOKENS.md
      details: Added 'CSS @keyframes' to README features list. Added comprehensive 'CSS @keyframes Animations' section to TOKENS.md with examples for basic keyframes, from/to keywords, complex animations, and component references.
      change_type: docs
      scope: docs
next_steps:
    - summary: Document states section in token format documentation
      details: Update TOKENS.md to show states alongside variants and sizes
      priority: med
      scope: docs
    - summary: Consider adding keyframe validation
      details: Validate frame selectors are valid CSS (percentages, from/to keywords)
      priority: low
      scope: pkg/tokens
---
schema_version: "1"
timestamp: "2026-02-07T12:22:09-08:00"
commit_hash: ""
changes:
    - summary: Add version command with build-time info
      details: |
        Added tokenctl version command showing version, git commit, and build time.
        Makefile now injects version info via ldflags during build and install.
      change_type: feature
      scope: cmd/tokenctl
    - summary: Add body background and foreground colors to CSS reset
      details: |
        Body element now sets background-color: var(--color-background) and
        color: var(--color-foreground) in the reset layer. Ensures theme colors
        apply immediately without requiring additional CSS.
      change_type: fix
      scope: pkg/generators
    - summary: Support dual theme directory layouts in loader
      details: |
        LoadThemes now checks both rootPath/themes/ and rootPath/tokens/themes/.
        Supports both "tokenctl build tokens" (tokens dir) and "tokenctl build ."
        (project root) invocations.
      change_type: fix
      scope: pkg/tokens
    - summary: Remove completed AUDIT_TODO.md
      details: All 34 audit items have been addressed; tracking file no longer needed.
      change_type: other
      scope: docs
next_steps:
    - summary: Document states section in token format documentation
      details: Update TOKENS.md to show states alongside variants and sizes
      priority: med
      scope: docs
