// tokenctl/pkg/derive/params.go
//
// Theme derivation: a small set of controls (hue, chroma, tint,
// saturation, mode, typography, density) expands into the full set of
// semantic colour tokens plus typography and density artifacts.
//
// The math is a port of the retired tokenctl-extension's theme-engine.ts.
// The extension is gone; the derivation is what was worth keeping. Golden
// fixtures in testdata/derive/goldens are generated by running the
// original TypeScript and pin this port to it — see
// tools/derive-goldens/regenerate.sh.
package derive

import "fmt"

// Params fully describes a derived theme.
type Params struct {
	Hue         float64 // 0–360, OKLCH hue angle
	Chroma      float64 // OKLCH chroma of the primary; clamped to 0.4
	IsDark      bool    // dark mode instead of light
	Tint        float64 // 0–100: how much the hue bleeds into neutrals
	Saturation  float64 // 0–150: global chroma multiplier, 100 = normal
	FontPairing string  // key into TypographySystems
	Density     float64 // 75–130: dimension scale, 100 = default
}

// DefaultParams matches the engine's DEFAULT_PARAMS.
var DefaultParams = Params{
	Hue:         250,
	Chroma:      0.20,
	IsDark:      false,
	Tint:        30,
	Saturation:  100,
	FontPairing: "system",
	Density:     100,
}

// Bounds of each control, as documented by the engine.
const (
	TintMin       = 0.0
	TintMax       = 100.0
	SaturationMin = 0.0
	SaturationMax = 150.0
	DensityMin    = 75.0
	DensityMax    = 130.0
)

// Preset is a named starting point: a hue and chroma pair.
type Preset struct {
	Name   string
	Hue    float64
	Chroma float64
	Swatch string // representative hex, for pickers
}

// Presets are the engine's eight built-ins, in its order.
var Presets = []Preset{
	{Name: "Blue", Hue: 250, Chroma: 0.20, Swatch: "#3b6de0"},
	{Name: "Purple", Hue: 290, Chroma: 0.18, Swatch: "#8b5cf6"},
	{Name: "Green", Hue: 155, Chroma: 0.18, Swatch: "#10b981"},
	{Name: "Amber", Hue: 75, Chroma: 0.16, Swatch: "#d97706"},
	{Name: "Red", Hue: 25, Chroma: 0.20, Swatch: "#dc2626"},
	{Name: "Teal", Hue: 195, Chroma: 0.14, Swatch: "#0d9488"},
	{Name: "Pink", Hue: 350, Chroma: 0.18, Swatch: "#ec4899"},
	{Name: "Slate", Hue: 250, Chroma: 0.02, Swatch: "#64748b"},
}

// PresetByName looks a preset up case-insensitively.
func PresetByName(name string) (Preset, bool) {
	for _, p := range Presets {
		if equalFold(p.Name, name) {
			return p, true
		}
	}
	return Preset{}, false
}

// PresetNames lists preset names in declaration order.
func PresetNames() []string {
	names := make([]string, len(Presets))
	for i, p := range Presets {
		names[i] = p.Name
	}
	return names
}

// Validate reports params outside the engine's documented ranges.
// The engine clamps silently; tokenctl refuses, because a CLI that
// accepts saturation=900 and quietly renders saturation=150 teaches the
// caller a control range that does not exist.
func (p Params) Validate() error {
	if p.Tint < TintMin || p.Tint > TintMax {
		return fmt.Errorf("tint %g out of range %g–%g", p.Tint, TintMin, TintMax)
	}
	if p.Saturation < SaturationMin || p.Saturation > SaturationMax {
		return fmt.Errorf("saturation %g out of range %g–%g", p.Saturation, SaturationMin, SaturationMax)
	}
	if p.Density < DensityMin || p.Density > DensityMax {
		return fmt.Errorf("density %g out of range %g–%g", p.Density, DensityMin, DensityMax)
	}
	if p.Hue < 0 || p.Hue > 360 {
		return fmt.Errorf("hue %g out of range 0–360", p.Hue)
	}
	if p.Chroma < 0 {
		return fmt.Errorf("chroma %g must not be negative", p.Chroma)
	}
	if _, ok := TypographySystemByKey(p.FontPairing); !ok {
		return fmt.Errorf("unknown font pairing %q (see `tokenctl derive --list`)", p.FontPairing)
	}
	return nil
}

func equalFold(a, b string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range len(a) {
		ca, cb := a[i], b[i]
		if 'A' <= ca && ca <= 'Z' {
			ca += 'a' - 'A'
		}
		if 'A' <= cb && cb <= 'Z' {
			cb += 'a' - 'A'
		}
		if ca != cb {
			return false
		}
	}
	return true
}
